os:
 - linux
 - osx

dist: trusty
addons:
 apt:
  sources:
   - sourceline: "deb http://archive.ubuntu.com/ubuntu trusty universe"
  packages:
   - ocl-icd-opencl-dev

language: c
compiler:
 - gcc
 - clang

script: make && ./clinfo
